language: python
os: linux
python:
  - 3.6
  - 3.7
  - 3.8
install:
    - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    - bash miniconda.sh -b -p $HOME/miniconda
    - source "$HOME/miniconda/etc/profile.d/conda.sh"
    - conda config --set always_yes yes --set changeps1 no
    - conda update -q -n base -c defaults conda
    - conda info -a
    - echo $TRAVIS_PYTHON_VERSION
    - conda env create -n test python=$TRAVIS_PYTHON_VERSION --file environment-dev.yml
    - conda activate test
    - conda install codecov pytest-cov
    - conda list
    - python setup.py build
    - python setup.py develop
script:
    - flake8 process_nwb tests
    - preprocess_folder -h
    - pytest -sv --cov=./ tests
    - sphinx-build -W -b html docs/source docs/build
after_success:
    - codecov
