name: process_nwb tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  run-tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.7", "3.8", "3.9"]
    steps:
      - name: Test process_nwb
        uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then python -m pip install -r requirements.txt; fi
          python -m pip install flake8 codecov pytest-cov sphinx-rtd-theme sphinx-gallery
          python -m pip install -e .
      - name: Lint with flake8
        run: |
          python -m flake8 src/process_nwb tests
      - name: Test with pytest
        run: |
          python -m pytest -sv --cov=./ tests
      - name: Build docs
        run: |
          sphinx-build -W -b html docs/source docs/build
      - name: Codecov
        run: |
          python -m codecov
